title: Aditya Thakare
logo: /assets/img/AdityaThakare.jpeg
description: AI Engineer & Data Scientist. Welcome to my professional portfolio.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
